# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170118_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
