# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170118_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='message',
            name='latitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='longitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
